# Generated by Django 4.2.6 on 2023-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_profile_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
    ]
