# Generated by Django 4.2.6 on 2023-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_room',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Токен чата'),
        ),
    ]
