# Generated by Django 4.2.6 on 2023-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_profile_unique_together_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_code',
            field=models.CharField(max_length=4, null=True, verbose_name='Код авторизации'),
        ),
    ]
