# Generated by Django 4.2.6 on 2023-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sending_time',
            field=models.DateTimeField(null=True, verbose_name='Время отправки SMS'),
        ),
    ]
