# Generated by Django 4.2.6 on 2023-11-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_profile_authorization_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='authorization_attempts',
        ),
    ]
