# Generated by Django 4.2.6 on 2023-11-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_profile_authorization_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='authorization_attempts',
            new_name='auth_attempts',
        ),
    ]
